services:
  backend:
    build:
      context: ./backend
    container_name: assistente-negocios-backend
    ports:
      - "8010:8010"
    volumes:
      - ./data:/code/data:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: assistente-negocios-frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped
